version: '3.8'
services:
  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    #volumes:
    #  - ./back:/app


  frontend:
    build:
      context: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend


#volumes:
#  db_data:
